### ISSUE TITLE
Bump syn for crates lisp_util and lisp_macros

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#142]
We are using quite outdated versions of the syn crate and the version used in lisp_util is even older. The code of lisp_util doesn't work with newer versions and needs to be adjusted(I think we had problems in remacs with it and used this old version because we couldn't get it to work with the version used in lisp_macros). Maybe it makes sense to put the code into one crate.

lisp_util: version = "0.11.11"
lisp_macros: version = "0.15.26"

**Comment by declantsien** [comment]
syn to v2
Alone with [`proc-macro2` to v1](https://github.com/emacs-ng/emacs-ng/pull/583)
[darling to 0.20](https://github.com/emacs-ng/emacs-ng/pull/565)
and quote to v1
