### ISSUE TITLE
Compilation error:  undefined symbol reference XML_GetBuffer

### ISSUE THREAD

**Issue by kostafey** [emacs-ng/emacs-ng#148]
```
   Compiling dprint-plugin-typescript v0.37.0
    Finished release [optimized] target(s) in 26m 13s
  CCLD     temacs
/usr/bin/ld: .././rust_src/target/release/libemacsng.a(fcxml.o): undefined symbol reference «XML_GetBuffer»
//lib/x86_64-linux-gnu/libexpat.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:745: recipe execution error for target «temacs»
make[1]: *** [temacs] Error 1
```

**Comment by DavidDeSimone** [comment]
Thank you for the report - was this with `./configure --with-webrender`, and if so, does this issue also happen with just `./configure`?

**Comment by kostafey** [comment]
> was this with ./configure --with-webrender

Yes.

> does this issue also happen with just ./configure

No, everything compiles well.

**Comment by brotzeit** [comment]
@kostafey do you still encounter this issue with the latest changes ?

**Comment by declantsien** [comment]
This `undefined reference` is that build with webrender requires fontconfig,
before we didn't add fontconfig to the set of libraries to be linked from `configure.ac`.
This issue should not happen anymore.
Please reopen if this issue persists.
