### ISSUE TITLE
What Emacs version are you building on top of?

### ISSUE THREAD

**Issue by cjohansson** [emacs-ng/emacs-ng#149]
Would be nice to know what Emacs version you are building onto and whether there are Emacs functions that are missing in this project that is available in vanilla Emacs.

Thanks for an interesting project! Will be following this development now when remacs has lost momentum

**Comment by brotzeit** [comment]
We are syncing with native-comp branch every few weeks(I didn't do it recently since I've read about issues with some packages with the latest native-comp branch changes). Do you think we should put the latest merged commit somewhere in the readme or do you have a different idea ?

**Comment by cjohansson** [comment]
Ok sounds great, yes I think that would be a good idea, or a date when the latest merge took place so people can now how up to date this additive layer is

**Comment by brotzeit** [comment]
@DavidDeSimone Although it's a good first issue, I did it because I think it's an info that many people are interested in.
