### ISSUE TITLE
Convert JavaScript.rs to use deno_core::error::AnyHow

### ISSUE THREAD

**Issue by DavidDeSimone** [emacs-ng/emacs-ng#175]
There are a large number of potential error and result types contained in JavaScript.rs. When building that module, I made the decision to convert all errors into IoError via calls to map. 

Deno solves this problem by using AnyHow, which they expose via the deno_core crate. They also expose helper functions like "deno_core::error::generic_error" to make using that error system easier.

Since deno uses AnyHow, I think it's worth while to convert the JavaScript related code to use it. Benefits are improved consistency across error producing calls, and less boilerplate

**Comment by wolf4ood** [comment]
Hi @DavidDeSimone 

I should have sometime for working on this. Do you know if converting to anyhow can cause so breaking changes on the JS/TS side ?

**Comment by jman-schief** [comment]
thanks for volunteering :crab:  :-)

**Comment by DavidDeSimone** [comment]
It shouldn't cause any breaking changes - there may be some cases
where the error message exposed to the user may change, but it will
likely be for the better.

**Comment by DavidDeSimone** [comment]
Complete
