### ISSUE TITLE
error: implicit declaration of function 'unload_comp_unit'

### ISSUE THREAD

**Issue by nickali** [emacs-ng/emacs-ng#195]
Hello, 

I had previously done a build a couple of weeks ago and it went fine. I did a pull again today and got the following error when I did a make:

```
alloc.c:3160:7: error: implicit declaration of function 'unload_comp_unit' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

      unload_comp_unit (cu);
      ^
1 error generated.
make[1]: *** [alloc.o] Error 1
make: *** [src] Error 2
make: *** Waiting for unfinished jobs....
```
Sequence to do the build:

./autogen.sh
./configure
./make -j 4

I'm trying to do this on MacOS 11.2.3 and

```
❯ rustup --version
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.51.0 (2fd73fabe 2021-03-23)`
```
and
```
❯ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by brotzeit** [comment]
Hi, thanks for the bug report. We have done an upstream merge recently and this seems related. Can you do me a favor and test the latest native-comp commit in emacs ? Unfortunately we have no OSX users in the community yet and we didn't add mac to our tests but we already have an issue for this I think.

**Comment by black7375** [comment]
Maybe it's my PR.. #185
I only tested it on Linux because there was no Mac.

I will try to take compatibility measures.
First, I see if there are any changes upstream([emacs:master](https://github.com/emacs-mirror/emacs), [emacs:feature/native-comp](https://github.com/emacs-mirror/emacs/tree/feature/native-comp), [emacs:feature/native-comp-macos-fixes](https://github.com/emacs-mirror/emacs/tree/feature/native-comp-macos-fixes)).

Second, I will create a workflow that performs build tests.
The GitHub action allows you to test whether a build is possible with a Mac.
However, Windows build is not sure. #47

Finally, There are plans to investigate the compatibility of major packages.
It will probably be a form of refactoring my settings and looking at it

**Comment by black7375** [comment]
There are no new changes to `alloc.c.` in the upstream.
I will start working on the test workflow from tomorrow.

**Comment by nickali** [comment]
Pulling commit [79b8b6c](https://github.com/emacs-mirror/emacs/commit/79b8b6ca45ad707d86244882430e275efd95cdb9) from emacs:feature/native-comp builds and runs fine.

**Comment by black7375** [comment]
Thank you for the information.
I will merge the upstream first and then proceed with the build test.

**Comment by DavidDeSimone** [comment]
One thing our project does different then mainline is we default to using -DEMACS_EXTERNAL_INLINE . That might be related? Just a thought. 

We define that so we can call inline methods from the Rust layer.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/112957800-532fd200-9131-11eb-8450-099b19c4d777.png)

It took quite a while, but I can now be sure of upstream bugs.
I succeeded in reproducing the bug with Docker for OSX. (OS install process takes a very long time. :sweat_smile:  :sweat_smile: )

```shell
git clone -b feature/native-comp https://github.com/emacs-mirror/emacs.git
./autogen.sh
./configure
./make -j4
```

**Comment by ubolonton** [comment]
Yeah it looks like a native-comp bug. 

The function's definition in `comp.h` is inside a `#ifdef HAVE_NATIVE_COMP`, but its usage in `alloc.c` is inside a runtime check.

**Comment by brotzeit** [comment]
@nickali Can you please confirm that it works with `./configure with_nativecomp=yes`.

**Comment by nickali** [comment]
@brotzeit I tried it with a fresh clone. I still get the same error.

**Comment by nickali** [comment]
Quick update. 

I just did a git pull and ran the following commands. It works now.

export LDFLAGS=-L/usr/local/Cellar/libgccjit/10.2.0_1/lib/gcc/10
./autogen.sh
./configure --with-native-compilation
make -j 6

Without the LDFLAGS command, it can't find libgccjit when its installed from homebrew.

**Comment by black7375** [comment]
Nice. I'll test it.

**Comment by nickali** [comment]
Not really sure if this is any help, below is how I got [master](https://github.com/emacs-ng/emacs-ng/tree/99d0df3e1a839f26709ce08ca38823c74b5a8ce2) to build and run. This is running Homebrew gcc 11.1.0.

```shell
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:${PATH}"
export CFLAGS=-I/usr/local/Cellar/gcc/11.1.0/include
export LDFLAGS="-L/usr/local/Cellar/gcc/11.1.0/lib/gcc/11 -I/usr/local/Cellar/gcc/11.1.0/include"
export LIBRARY_PATH="/usr/local/Cellar/gcc/11.1.0/lib/gcc/11:${LIBRARY_PATH:-}"

./autogen.sh
./configure --with-native-compilation
./make
```

**Comment by brotzeit** [comment]
Is this still an issue ?

**Comment by Atemu** [comment]
emacs-ng still doesn't compile on Darwin because of a linker error but it seems to get past compiling alloc.c for me now.
