### ISSUE TITLE
Mac Build Test with native-comp enabled

### ISSUE THREAD

**Issue by black7375** [emacs-ng/emacs-ng#196]
The Mac also performs build tests. #195

It will be in the form of adding to [.github/workflows/test.yml](https://github.com/emacs-ng/emacs-ng/blob/master/.github/workflows/test.yml)

**Comment by declantsien** [comment]
Instead of updating [.github/workflows/test.yml](https://github.com/emacs-ng/emacs-ng/blob/master/.github/workflows/test.yml), since the macOS tests is already way slower than the Ubuntu ones.

Mac builds [here](https://github.com/emacs-ng/emacsng-darwin-builds) are with native-comp enabled.
