### ISSUE TITLE
Don't generate bindings by default

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#203]
The bindings that are generated by bindgen are now included in the crate emacs #201. However they are still created every time we build emacs-ng. We need to put this code from src/Makefile.in into a phony target and make it optional to reduce the build time.

```
$(DEFINITIONS_FILE) $(BINDINGS_FILE) $(GLOBALS_FILE): $(filter-out ./macuvs.h,$(HEADERS)) $(rust_srcdir)/wrapper.h \
							$(rust_srcdir)/remacs-bindings/Cargo.toml \
							$(rust_srcdir)/remacs-bindings/src/main.rs
	$(MKDIR_P) $(dir $@)
	RUSTFLAGS="$(RUSTFLAGS)" \
	EMACS_CFLAGS="$(EMACS_CFLAGS)" \
	$(CARGO_RUN) --release --manifest-path=$(rust_srcdir)/remacs-bindings/Cargo.toml -- $(basename $(notdir $@)) $@
	touch $@
```

**Comment by brotzeit** [comment]
Maybe it's better if we don't do it this way since we would have to include the bindings that are needed by each feature, even if emacs-ng is not compiled with all features. It also seems that the bindings are generated quite fast so I think it's probably not worth it.

**Comment by declantsien** [comment]
This now implemented using [build.rs](https://github.com/emacs-ng/emacs-ng/blob/master/rust_src/crates/emacs/build.rs.in). I guess this issue is no long relevant.
