### ISSUE TITLE
Darwin Nix build dependency compiler-rt fails with: lipo: architecture specifed for fat input file

### ISSUE THREAD

**Issue by Atemu** [emacs-ng/emacs-ng#222]
**Describe the bug**

```
fatal error: lipo: architecture specifed for fat input file: /tmp/nix-build-compiler-rt-10.0.1.drv-0/compiler-rt-10.0.1.src/build/lib/builtins/libclang_rt.cc_kext_i386_osx.a (architectures can't be specifed for fat input files)
make[2]: *** [lib/builtins/CMakeFiles/clang_rt.cc_kext.dir/build.make:83: lib/darwin/libclang_rt.cc_kext.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:1185: lib/builtins/CMakeFiles/clang_rt.cc_kext.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Not sure why it's any different from regular Nixpkgs anyways; do you guys patch llvmPackages in some way?

**To Reproduce**
Steps to reproduce the behavior. What were the options you passed to configure?

```shell
nix-build
```

**Expected behavior**

**OS**
Which os do you use? (`uname -a`)

Darwin

**Error callstack**

**Comment by GTrunSec** [comment]
Sorry, I did not pass the build on Darwin.  check the CI logs https://github.com/GTrunSec/emacs-ng/runs/2444015117.

> What were the options you passed to configure?

Also, you can modify the flake.nix to override the flags of configure.

**Comment by Atemu** [comment]
The problem in my case isn't even emacs-ng itself but one of its dependencies, compiler-rt.

If the mac machine in the CI can build that though (it gets to building emacs-ng), it must be something wrong with my setup.

**Comment by GTrunSec** [comment]
>If the mac machine in the CI can build that though (it gets to building emacs-ng), it must be something wrong with my setup.

So, I have created the new issue #228.  if you have any resources to support the darwin platform, please feel free to PR.

**Comment by Atemu** [comment]
I just tested your branch and that doesn't try to build compiler-rt; it's not my setup then.

`nix build github:emacs-ng/emacs-ng` still fails though, can you reproduce that?

**Comment by Atemu** [comment]
Seems to have been resolved for one reason or another.
