### ISSUE TITLE
Remove unused code from remacs-lib

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#23]
I think we should delete the folder completely since we don't seem to use the code. Or am I missing something ?

**Comment by DavidDeSimone** [comment]
The only function I need to better familiarize myself with is `docfile::scan_rust_file`, as I am unsure if that would still be useful. Otherwise I think the 'remacs-lib' should be removed.

**Comment by DavidDeSimone** [comment]
After looking into it, docfile::scan_rust_file is actually critical for the macro `def_lisp_sym!` in rust, which is equivalent to `DEF_SYM` in C. We can rework the crate structure to allow for the production of a static library that can link against it, but we don't want to delete it.
