### ISSUE TITLE
Prepare Dockerfiles to build emacs-ng

### ISSUE THREAD

**Issue by jman-schief** [emacs-ng/emacs-ng#235]
The idea is to build a set of Dockerfiles to:
- Build emacs-ng in the CI
- Enable people to build emacs-ng themselves from scratch and without any context

Ideally building for the most common Linux distributions.

I'll start by cracking a Debian image.

**Comment by jman-schief** [comment]
I think for now these files will suffice. In case we want to support a new distro we can always prepare a new Dockerfile image (or it can be contributed)

**Comment by brotzeit** [comment]
Thanks for your work!

**Comment by DavidDeSimone** [comment]
Good work, thank you.
