### ISSUE TITLE
Building: emacs-ng seems to be unable to find system libs which is found by standard emacs

### ISSUE THREAD

**Issue by Delanii** [emacs-ng/emacs-ng#263]
**Describe the bug**
Reposted from reddit per recommendetion. Original post: https://www.reddit.com/r/emacsng/comments/n8kiuq/building_from_source_emacsng_seems_to_be_unable/

emacs-ng seems to be unable to find system libraries which standard emacs is able to find and use in `.configure` results automatically.

Sample output of `./configure --with-native-compilation --with-webrender` on current emacs-ng source (part omitted for clarity):

```
  Does Emacs use -ljpeg?                                  no
  Does Emacs use -ltiff?                                  no
  Does Emacs use a gif library?                           no 
  Does Emacs use a png library?                           no 
  Does Emacs use -lrsvg-2?                                no
  Does Emacs use cairo?                                   no
  Does Emacs use -lgnutls?                                yes
  Does Emacs use -lxml2?                                  yes
  Does Emacs use -lfreetype?                              no
  Does Emacs use HarfBuzz?                                no
```

But if I am building standard emacs from source I get following output from `./configure --with-native-compilation` (again parts omitted):

```
  Does Emacs use -ljpeg?                                  yes
  Does Emacs use -ltiff?                                  yes
  Does Emacs use a gif library?                           yes -lgif
  Does Emacs use a png library?                           yes -lpng16 -lz
  Does Emacs use -lrsvg-2?                                yes
  Does Emacs use cairo?                                   yes
  Does Emacs use -lgnutls?                                yes
  Does Emacs use -lxml2?                                  yes
  Does Emacs use -lfreetype?                              yes
  Does Emacs use HarfBuzz?                                yes
```

I have tryed a few inclusion flags I could think of the get at least Harfbuzz recognized by emacs-ng, but none of them worked (but I never done that before, so I might doing that incorrectly).

According to reddit, this behaviour is not intended and should not even happen, but that is what I get from `./configure`. Could this be fixed on user side?

**To Reproduce**

```shell
git clone git://git.savannah.gnu.org/emacs.git
cd emacs
./autogen.sh
./configure --with-native-compilation
```

compare with:

```shell
git clone https://github.com/emacs-ng/emacs-ng
cd emacs-ng
./autogen.sh
./configure --with-native-compilation --with-webrender
```

**Expected behavior**
emacs-ng detects all appropriate dev headers and libraries in same manner as standard emacs. With that gives the same output of `.configure` script as standard emacs.

**OS**
Manjaro KDE

**Error callstack**
None

**Comment by black7375** [comment]
https://github.com/emacs-ng/emacs-ng/issues/227#issuecomment-831287036

> `--with-x-toolkit`, `--with-xft,` `--with-cairo` and `--with-harfbuzz` are not needed when using `--with-webrender` at the same time.

**Comment by harryfei** [comment]
Webrender have no image support currently.

**Comment by Delanii** [comment]
@harryfei And how could that be resolved until he does? Wouldnt it be plausible then not execute webrender process when opening pdf or an image? There might be issue with org-mode having inline display of images though, or latex pdf previews ...

**Comment by harryfei** [comment]
@Delanii Sorry, my words mislead you. `webrender` crate support image rendering. `emacs-ng`'s `webrender` backend doesn't support yet.
We just need to add some code to render image in webrender backend.

**Comment by Delanii** [comment]
Oh, OK, then indeed this should be pointed out in the documentation that webrender deals with all the stuff that is in standard emacs dealt with standard libraries. Also, pdf has to be implemented too (again via webrender?)
