### ISSUE TITLE
Find more elegant way to add globals that are located in rust files

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#289]
Currently, we are adding globals that are defined in rust by using `make-docfile` which calls `scan_rust_file` from `rust_src/remacs-lib/docfile.rs`. Since we now have multiple crates it would be better if we could find a different way so we don't have to add the path of each crate to `src/Makefile.in`. 

```make
$(AM_V_at)$(libsrc)/make-docfile -d $(srcdir) \
  $(SOME_MACHINE_OBJECTS) $(obj) $(rust_srcdir)/src/*.rs $(rust_srcdir)/crates/js/src/*.rs $(rust_srcdir)/crates/ng_async/src/*.rs > $(etc)/DOC
```

**Comment by declantsien** [comment]
I've added a rust binary to computing the Rust sources which may have the lisp_fn/defvar_lisp/def_lisp_sym based on the currently enabled Cargo features. This now happening in configure stage.

So now we can just add a new crate and add `emacs-sys` and `lisp-macro` as dependencies, and start to write lisp objects. No extra configuration is needed.

The `lisp_fn` can  also be written in nest module like `crate/some-crate/src/module/nest.rs`
