### ISSUE TITLE
Use Cargo.toml instead of Cargo.lock to pin us to a version of our Deno fork

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#292]
Came up in #268

**Comment by DavidDeSimone** [comment]
The best way I can think of doing this is to use a branch per deno release. I.e. when I make an upgrade to deno 1.X.Y, we set Cargo.toml to use our deno fork pointing to the head of the branch for that version. 

I also need to transition us from using my deno fork to having emacs-ng maintain a deno fork. I think the easiest way to do that is to have the emacs-ng org fork my deno fork.

**Comment by harryfei** [comment]
```
deno = { git = "https://github.com/DavidDeSimone/deno"" , rev = "a5cc46feb0" }
```
Does just using `rev` in Cargo.toml match our case?
