### ISSUE TITLE
Move parsing related code from ng_async to seperate crate

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#300]
This came up in https://github.com/emacs-ng/emacs-ng/pull/275#issuecomment-843489247. I think we shouldn't make too extensive use of the ng_* naming for crates.

cc @DavidDeSimone

**Comment by DavidDeSimone** [comment]
Agree 100% - ng_async was named when the project was young and I don't think it is a good naming convention going forward.

**Comment by brotzeit** [comment]
So what would be a good name for the "parsing" crate. json, lsp, lsp-json ? Any ideas ?

**Comment by DavidDeSimone** [comment]
I vote for lsp-json, which is basically what it is
