### ISSUE TITLE
Failing to build with Nix

### ISSUE THREAD

**Issue by JavaCafe01** [emacs-ng/emacs-ng#301]
**Describe the bug**
I'm having some trouble building with Nix. I have the cachix set up properly, and after running nix build github:emacs-ng/emacs-ng, I get the following error:

```bash
error: builder for '/nix/store/9962x85cl1fj5aqr4mbw8d76k7p4jrz5-remacsLibDeps-vendor.tar.gz.drv' failed with exit code 1;
       last 6 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/vhvxc1j073yn2p6gxxwfbps03q3rm9qs-source/rust_src/remacs-lib
       > source root is remacs-lib
       > patching sources
       > building
       > cp: cannot create directory '/build/crates': No such file or directory
       For full logs, run 'nix log /nix/store/9962x85cl1fj5aqr4mbw8d76k7p4jrz5-remacsLibDeps-vendor.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/dqrhlnigppqn2gdhlflb9nqyl2w54gf6-emacsNg-rust.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y12vvyccrn63sh65cvndxh9ln59011i8-emacsNg-bc889e9.drv' failed to build

```

**To Reproduce**
* Set up cachix
* build with `nix build github:emacs-ng/emacs-ng`

**Expected behavior**
A successful build.

**OS**
NixOS

**Comment by GTrunSec** [comment]
Cleanup the emacs-ng cache first. looks like this issue was built in older rev.  CI check https://github.com/emacs-ng/emacs-ng/runs/2739877680.

**Comment by GTrunSec** [comment]
Thanks for the report, Fixed by https://github.com/emacs-ng/emacs-ng/pull/309
