### ISSUE TITLE
macOS nix-build: "make[1]: *** [Makefile:687: ../rust_src/crates/emacs/src/definitions.rs] Killed: 9"

### ISSUE THREAD

**Issue by Atemu** [emacs-ng/emacs-ng#312]
**Describe the bug**

When building emacs-ng on macOS with Web~~reader~~render, something gets killed with signal 9 during the build. I don't think this is an OOM since I've never seen something get reaped on OSX (it does very aggressive swapping).

Getting killed with -9 can sometimes mean that macOS doesn't allow you to be executed because you're lacking an apple-blessed signature or whatever; that might be a lead.

**To Reproduce**
Steps to reproduce the behavior. What were the options you passed to configure?

```patch
diff --git a/flake.nix b/flake.nix
index 073326c19b..579c0082bc 100644
--- a/flake.nix
+++ b/flake.nix
@@ -195,7 +195,7 @@
           librusty_v8 = prev.callPackage ./nix/librusty_v8.nix { };
 
           emacsNg = with prev; let
-            withWebreader = false;
+            withWebreader = true;
           in
           (
             final.emacsGcc.override
@@ -248,6 +248,7 @@
                   "--with-zlib"
                   "--with-dumping=pdumper"
                 ] ++ lib.optionals withWebreader [
+                  "--without-ns"
                   "--with-webrender"
                 ] ++ lib.optionals stdenv.isLinux [
                   "--with-dbus"
```

```shell
git checkout 8c9cf76c03c9aa3f84827b4cc5a4d31a779aebc2
nix-build
```

**Expected behavior**

**OS**
Which os do you use? (`uname -a`)

Darwin MacBook-Pro 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin

**Error callstack**

**Comment by harryfei** [comment]
Webrender feature can't build on macOS currently.

**Comment by GTrunSec** [comment]
Also, I have no idea how to build emacsNg with Nix on darwin. b(Maybe the current problem was from the older version of darwin-SDK)

**Comment by Atemu** [comment]
> Webrender feature can't build on macOS currently.

I see, having the build fail because of a process being killed seemed unusual though.

> I have no idea how to build emacsNg(without webrender) with Nix on darwin. (Maybe the current problem was from the older version of darwin-SDK)

The current non-webrender master gets quite far actually, only fails to link in the end.

**Comment by declantsien** [comment]
You can use nix flake here
https://github.com/declantsien/emacs-webrender/actions/runs/3835526145
to build webrender on macOS.
