### ISSUE TITLE
Can we include the latest native comp changes

### ISSUE THREAD

**Issue by declanqian** [emacs-ng/emacs-ng#326]
Can we include the native comp changes from [emacs master branch]( https://github.com/emacs-mirror/emacs/commit/fe1b72d21658cf3acfaae3b092bc53a2fe479f0f)
  Some packages I use are reporting issues about `native-comp-deferred-compilation-deny-list`

  After I manually merged the changes from emacs mirror, the issues are gone.

  Really liked the webrender/libgit idea.

**Comment by declanqian** [comment]
Just read the document
https://github.com/emacs-ng/emacs-ng#overview
> emacs-ng is based off of the master branch of emacs, and regularly merges in the latest changes.

So this is not an issue then

**Comment by brotzeit** [comment]
@declanqian it's possible that we are missing recent changes. If you say it works with latest master we should keep this issue open.

**Comment by brotzeit** [comment]
@declanqian does it work now ?

**Comment by declanqian** [comment]
Yeah, it's working now. :+1: 
Thought you guys have some protocol to merge upstream changes. Didn't want
to rush about it.

**Comment by brotzeit** [comment]
Not really.
