### ISSUE TITLE
Winit frame failed to scroll when doing isearch

### ISSUE THREAD

**Issue by declantsien** [emacs-ng/emacs-ng#332]
No idea how to describe this issue in text. Created a screen-cast

https://user-images.githubusercontent.com/51986034/122634290-e57fba80-d10f-11eb-8a34-04db9a59928e.mp4

**OS**
Linux thinkpadx1extreme 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64 GNU/Linux
Also on wayland using Sway with env `MOZ_ENABLE_WAYLAND=1`.

```shell
./configure --with-libgit --with-webrender --with-native-compilation --with-wide-int
```

**Comment by declantsien** [comment]
This seems to be related to winit(frame implementation) part. Webrender with PGTK does not have this issue.

**Comment by declantsien** [comment]
Here is a screencast using PGTK with webrender.

https://user-images.githubusercontent.com/51986034/222114710-35510731-9b31-47ea-a60d-b5cf097acefd.mp4

**Comment by 2e0byo** [comment]
I can't confirm under tao either, and I don't remember it when I was using winit.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> I can't confirm under tao either, and I don't remember it when I was using winit.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/332#issuecomment-1450593230
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

Just did a little test on tao build. Its happening. How do you test?
Failed to scroll when doing isearch I mean
- `C-s`
- input some keywords
- keep hitting `C-s`

**Comment by 2e0byo** [comment]
Drat, I *can* confirm under Tao.

I run spacemacs/evil and tested with `/`---which runs `evil-ex-search-forward`, not `isearch`.  (Which works fine.)  Also `C-s` works, because it runs `isearch-repeat-forwards`.

Weirdly `isearch-repeat-forwards` works fine, but `isearch-forwards` doesn't.  (Same odd behaviour as in the original screencast.)

At any rate a workaround is to bind `C-s` to `isearch-repeat-forwards`.

**Comment by 2e0byo** [comment]
hahaha, that's mad.

You never know though, maybe someone's using wayland via vpc over a dial up link...
