### ISSUE TITLE
webrender frame in dark theme  background flashing when maximizing

### ISSUE THREAD

**Issue by declanqian** [emacs-ng/emacs-ng#340]
Webrender frame in dark theme  background flashing when maximizing,
while it works just fine in PGTK Emacs. I am using Sway in Wayland.
Demos in the screencast.

https://i.imgur.com/8pFc5xf.mp4

Any ideas what's happening there?

--
edit: fix typo

**Comment by harryfei** [comment]
I believe that this issue is fixed by other webrender changes in master branch.
Could you test it again?

**Comment by declanqian** [comment]
Indeed. Nice work. @harryfei
