### ISSUE TITLE
Document built-in packages use-package and straight

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#348]
Follow up issue of #346

**Comment by brotzeit** [comment]
I think we have to apply some modifications to make this change useful for users.

This is my straight config:

```
(setq byte-compile-warnings '(cl-functions))
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "~/home/straight.el/bootstrap.el" "~/.newemacs.d/"))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;;; https://github.com/raxod502/straight.el/blob/develop/README.md#integration-with-use-package
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
```

My config is quite old so I don't know if there's a better way to configure straight, but we have to define the location of the built-in straight.el package. It also seems it's necessary to add use-package as default method.

Any straight users here with an idea ?

**Comment by declanqian** [comment]
I am using this
```
(if (fboundp 'straight-use-recipes)
    (progn
      // copy some code from bootstrap.el
      )
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage)))  
```

I think basically what we need is just to setup some recipes
using `straight-use-recipes` and turn on some minor modes `straight-use-package-mode` etc.
I sent a pull request before to wrap this in a function called `straight-bootstrap`,
later deleted it by thinking it's not worth it.

I liked `package.el`'s `package-initialize` logic, but it can complicate thing up.

**Comment by brotzeit** [comment]
We could add the bootstrapping code to `/home/fredbert/ng_stuff/emacs-ng/lisp/emacs-lisp/emacs-ng.el`.

**Comment by declanqian** [comment]
Yeah, seems the right way to go.
It also simplifies my `.emacs` file. Let me do that.
