### ISSUE TITLE
Makefile target LIBEMACSNG_ARCHIVE is missing prerequisites

### ISSUE THREAD

**Issue by declanqian** [emacs-ng/emacs-ng#353]
The problem is that if edited some files from path `./rust_src/crates/webrender/src`,
invoking `make` again from the top dir. LIBEMACSNG_ARCHIVE target from `src/Makefile`
is no triggered.

A quick investigation is that
`$(LIBEMACSNG_ARCHIVE): globals.h $(rust_srcdir)/crates/emacs/src/** $(rust_srcdir)/crates/lisp_util/** $(rust_srcdir)/crates/lisp_macros/** $(rust_srcdir)/Cargo.* $(libsrc)/hashdir/target/$(CARGO_BUILD_DIR)/hashdir$(EXEEXT) $(DEFINITIONS_FILE) $(GLOBALS_FILE) $(BINDINGS_FILE)`
is missing some prerequisites.

Maybe we can utilize cargo [Dep-info files](https://doc.rust-lang.org/cargo/guide/build-cache.html#dep-info-files),
Otherwise, we need to update this line every time we add a new crate.

I am putting up a PR regarding this, currently it's only for `libemacsng.a`. If you guys think it's acceptable, I can do the same for `libremacs_lib`.

**Comment by brotzeit** [comment]
>  Otherwise, we need to update this line every time we add a new crate.

Yeah, we already have an open issue #289 (although it's kind of outdated)

I'm trying to understand why the build fails, but maybe somebody with more knowledge can also take a look.

cc @DavidDeSimone =)

**Comment by declanqian** [comment]
It's happens to me now locally. Will check.
Marked the PR WIP.

**Comment by declanqian** [comment]
Just made some progress. Need a small fix for [sed on macOS](https://stackoverflow.com/a/19457213).
I probably do this tomorrow.

Also, the nix error. Yeah, somebody with some nix knowledge would be very helpful.

Currently, I am still reading nix manual, plan to switch to NixOS...

**Comment by brotzeit** [comment]
@GTrunSec usually fixes our nix build =)
