### ISSUE TITLE
Pass make -j[N] to cargo -j [N]

### ISSUE THREAD

**Issue by declanqian** [emacs-ng/emacs-ng#356]
https://doc.rust-lang.org/stable/cargo/commands/cargo-build.html#miscellaneous-options

I saw `MAKEFLAGS = pw -j12 --jobserver-auth=4,5` from dump `make -p -j12`

**Comment by declanqian** [comment]
Ah, this is not a valid task. Since cargo already works well with make as `sub-make`.
https://github.com/rust-lang/cargo/issues/1744
https://github.com/rust-lang/cargo/pull/4110
I can see there are multi `rustc` processes from `top` when running `make -jN`

I guess the long first built time is inevitable then.

**Comment by brotzeit** [comment]
But it does not consider `-jN` right ?

**Comment by declanqian** [comment]
If you manually hardcore `-j12` to `src/Makefile.in`, also invoke make with
`make -j12`. You would get this message.

```
cargo build --release --manifest-path ../rust_src/Cargo.toml -j12
warning: a `-j` argument was passed to Cargo but Cargo is also configured with an external jobserver in its environment, ignoring the `-j` parameter
```

So Cargo already considers make's `-jN`, if that's what you are asking.

**Comment by brotzeit** [comment]
Ok, thanks.
