### ISSUE TITLE
Emacs-ng fails to build with nixOS (flakes) due to hash mismatch

### ISSUE THREAD

**Issue by shaunsingh** [emacs-ng/emacs-ng#371]
**Describe the bug**
Emacs-ng fails to build because of a hash mismatch, 

**To Reproduce**
I'm installing emacs-ng via nix using nix-flakes, and putting emacsNg-src as an input. I'm using the default configuration supplied with the flake. Upon `nixos-rebuild switch --flake`: 

```zsh
~/vimrc-dotfiles (main ✓) λ nixos-rebuild boot --flake .#shaunsingh-laptop
building the system configuration...
[0/1 built, 3 copied (92.6 MiB), 30.4 MiB DL] querying libmicrohttpd-0.9.71 on htt[0/243 built, 2/36/559 copied (195.0/3731.1 MiB), [0/243 built, 2/37/559 copied (215.3/3731.1 MiB), 67.0/676.7 MiB DL] fetching fribidi-1.0.10 from https://cache.ni[1/161/183 built,
error: hash mismatch in fixed-output derivation '/nix/store/mkrdawyagg69njg3mpyii3q9fqy38bhn-remacsLibDeps-vendor.tar.gz.drv':
         specified: sha256-wD0KBHtjVDfP2WCmb6XLhO6vrP4CY4zzAHQs93nvtUo=
            got:    sha256-w49ROzIvgdQpSrWHomtg6eEmssZFmgLsJ/optFSuaEY=
error: 1 dependencies of derivation '/nix/store/8arr6b5q6ybz3z04hymz7vzp5gxs9vn5-emacsNg-rust.drv' failed to build
error: 1 dependencies of derivation '/nix/store/iv8qgncmpvir03wbr58z0x40yjszz22k-emacsNg-19de734.drv' failed to build
error: 1 dependencies of derivation '/nix/store/whqwcbymg6z40ab2idk6gjhmp02wwx2k-emacsNg-19de734_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jwjjy81gdmvv5jlgalkygzvkrcwgvczc-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/aqq8mn3c77rg3ymn6y8sazr99skcvbbd-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d1payzavakisl55l87msm4cl07jilwx3-nixos-system-shaunsingh-laptop-21.05.20210817.97c5d0c.drv' failed to build
``` 

**Expected behavior**
emacs-ng should install as expected 

**OS**
Which os do you use? (`uname -a`)

```zsh
~/vimrc-dotfiles (main ✓) λ uname -a
Linux nixos 5.10.57 #1-NixOS SMP Sun Aug 8 07:05:24 UTC 2021 x86_64 GNU/Linux
```

According to the nixos discord server, the issue might be that "you are using git to fetch stuff in a FOD without deleting the .git folder, that causes issue as the remote seems to have changed and therefore the hash changes."

**Comment by black7375** [comment]
I think @GTrunSec is well aware of Nix.
Is it possible to bump?

**Comment by GTrunSec** [comment]
sure let me deal with that. also, you can refer to my emacs-flake example first https://github.com/GTrunSec/Coding-Dev-Env-With-NixFlake/tree/main/emacs

**Comment by GTrunSec** [comment]
check again : https://github.com/emacs-ng/emacs-ng/runs/3368712383

**Comment by GTrunSec** [comment]
> you are using git to fetch stuff in a FOD without deleting the .git folder, 

I'm really confusing, and I have been locked the rev via fetchgit in nvfetcher.

**Comment by shaunsingh** [comment]
>

**Comment by shaunsingh** [comment]
> https://github.com/GTrunSec/Coding-Dev-Env-With-NixFlake/tree/main/emacs

Thank you, I'll adjust my config a bit and try again

**Comment by shaunsingh** [comment]
Builds fine now!
