### ISSUE TITLE
Child frames do not render text exactly as parent.

### ISSUE THREAD

**Issue by ReggieMarr** [emacs-ng/emacs-ng#390]
**Describe the bug**
Child frame appears with minor font errors.

**To Reproduce**
Startup emacs, get git status of emacs-ng. produce child frame with ```(make-frame)``` then get git status of emacs-ng.

Built off #387 and  efaed29 with the following:
```shell
make clean
./configure --with-webrender --with-native-compilation --with-json
make -j 8
```

**Expected behavior**
Child frame should render fonts the same way as parent.

**OS**
Manjaro Gnome (Wayland) & Manjaro XFCE (X11)

Primary frame appears as follows:
![primary_frame](https://user-images.githubusercontent.com/13193444/131518100-c8342430-cd34-45ba-9d86-98e2e7a3ac9f.png)

![primary_terminal](https://user-images.githubusercontent.com/13193444/131519080-9c13a44a-f75c-4ef2-9bee-ce548c2cbfbe.png)

Child frame appears as this:

![secondary_frame](https://user-images.githubusercontent.com/13193444/131518228-f48d8e98-dd99-4187-8609-c7db0e7e9418.png)

![secondary_terminal](https://user-images.githubusercontent.com/13193444/131519047-708a2665-c0c7-422d-9442-d7f947102925.png)

Note that the child frame does not render the "Stashes" or "Recent Commits" Text. There are other examples that are more egregious as well which I can provide (notably when using [ement.el chat client](https://github.com/alphapapa/ement.el))

**Comment by declantsien** [comment]
Multi frame font issue should be resolved in master branch.
Please reopen if this issue persists.
