### ISSUE TITLE
`lisp_fn` `min` not working properly?

### ISSUE THREAD

**Issue by declantsien** [emacs-ng/emacs-ng#416]
To my understanding, `min` defines the minimal args needed. `min="2"` should
put `&optional` after the second arg when invoke `describe-function`?
The difference below is that `path: LispStringRef` vs `path: emacs::multibyte::LispStringRef`.

```
#[lisp_fn(min = "2")]
pub fn wr_api_capture(
    path: emacs::multibyte::LispStringRef,
    bits_raw: LispObject,
    start_sequence: LispObject,
)
```
-> `(wr-api-capture PATH &optional BITS-RAW START-SEQUENCE)`
```
#[lisp_fn(min = "2")]
pub fn wr_api_capture(
    path: LispStringRef,
    bits_raw: LispObject,
    start_sequence: LispObject,
)
```
-> `(wr-api-capture PATH BITS-RAW &optional START-SEQUENCE)`

**Comment by brotzeit** [comment]
Maybe `describe-function` needs updating. I remember that we applied several changes to the remacs code base in order to make elisp functionallity work with functions that are defined in rust(also jump to definition etc. -> #86).
