### ISSUE TITLE
Reorganize rust workspace

### ISSUE THREAD

**Issue by declanqian** [emacs-ng/emacs-ng#420]
I found rust code in our repo is kind of crowded.
At first I thought `rust_src` misused Cargo workspace, until I realized
it's a valid use case([root package](https://doc.rust-lang.org/cargo/reference/workspaces.html#root-package)).

However, I've came across several [failed compilations](https://github.com/declanqian/emacs-ng/runs/4219918236?check_suite_focus=true)

```
Compiling ng_module v0.1.0 (/home/runner/work/emacs-ng/emacs-ng/rust_src/crates/ng_module)
   Compiling rustls v0.19.0
error: couldn't read /home/runner/work/emacs-ng/emacs-ng/rust_src/crates/ng_module/out/ng_module_exports.rs: No such file or directory (os error 2)
  --> crates/ng_module/src/ng_module.rs:77:1
   |
77 | / include!(concat!(
78 | |     env!("CARGO_MANIFEST_DIR"),
79 | |     "/out/ng_module_exports.rs"
80 | | ));
   | |___^
   |
   = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)
```
I think `rust_src/build.rs` didn't executed before its'
decencies("ng_module", "ng_async") are resolved(compiled).

This issue aims:

- Move rust workspace to repo top-level
- Maybe use [Cargo workspace Virtual manifest](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-manifest)
- Global rust code generation(`c_exports.rs` etc) using make.
- ~~`definitions.rs`, `bindings.rs`, `globals.rs` are only for `crates/emacs`, can move inside it's `build.rs`?~~

**Comment by declanqian** [comment]
Maybe you @brotzeit can elaborate the
> other stuff we need to update like remacs-lib

from this https://github.com/emacs-ng/emacs-ng/pull/418#issuecomment-973148351

**Comment by brotzeit** [comment]
It's been a while since I've worked on the build stuff.

> Move rust workspace to repo top-level

Is this really common practice when using ffi with C code ?


> Maybe use Cargo workspace Virtual manifest

"When working with virtual manifests, package-related cargo commands, like cargo build, won't be available anymore. But, most of such commands support the --all option, will execute the command for all the non-virtual manifest in the workspace."

Does this mean we can't build the crates individually anymore ? IMO it's convenient to build a crate separately before building the whole workspace.


> Global rust code generation(c_exports.rs etc) using make.

Which advantages would we have using make ? I think using rust makes things a lot easier, given that we have lots of features that can be turned on and off.


> definitions.rs, bindings.rs, globals.rs are only for crates/emacs, can move inside it's build.rs?

The idea was to add a seperate crate for the generated bindings, but we would have to change the use of `LispObject` to make this possible. I gave up at some point and thought maybe somebody more experienced improves it in the future.

**Comment by brotzeit** [comment]
Ah and regarding the bug with ng_module, I'll try to reproduce.

**Comment by declanqian** [comment]
FTR, I don't want to force push any changes.

> Is this really common practice when using ffi with C code ?

I saw [Firefox](https://github.com/mozilla/gecko-dev) is using [a top-level Cargo.yml](https://github.com/mozilla/gecko-dev/blob/master/Cargo.toml).
The way we organize the rust code, made me think that Rust is not a primary(first–class) language.

> "When working with virtual manifests, package-related cargo commands, like cargo build, won't be available anymore. But, most of such commands support the --all option, will execute the command for all the non-virtual manifest in the workspace."
>
> Does this mean we can't build the crates individually anymore ? IMO it's convenient to build a crate separately before building the whole workspace.

I can't found the related info from [The Cargo Book](https://doc.rust-lang.org/cargo/index.html),  only found that `--all` from [this section](https://doc.rust-lang.org/cargo/commands/cargo-build.html#package-selection).
To my understanding, `cargo build` would works as usual. 

> Which advantages would we have using make ? I think using rust makes things a lot easier, given that we have lots of features that can be turned on and off.
> Ah and regarding the bug with ng_module, I'll try to reproduce.

I was able to reproduce [the issue](https://github.com/declanqian/emacs-ng/runs/4270621653?check_suite_focus=true) by [adding a build dep](https://github.com/declanqian/emacs-ng/commit/3927dd885d321014241fa8d001047a0501996689)

> The idea was to add a seperate crate for the generated bindings, but we would have to change the use of LispObject to make this possible. I gave up at some point and thought maybe somebody more experienced improves it in the future.

Too much information here. let's forget this one.

**Comment by declanqian** [comment]
Not worth it. Let me close it.
