### ISSUE TITLE
use-package and straight.el are not included in the nix version of emacs-ng

### ISSUE THREAD

**Issue by crazazy** [emacs-ng/emacs-ng#426]
**Describe the bug**
When getting the latest version of emacs-ng with nix, it is not possible to use use-package and straight.el without having to install them manually in your user-emacs folder

Upon further investigation, it seems that the folders that are supposed to house use-package and straight.el in the nix store are empty, so I assume that the submodules didn't get imported in the making of the flake

**To Reproduce**

```shell
nix-env -if https://github.com/emacs-ng/emacs-ng/archive/master.tar.gz -A defaultPackage.x86_64-linux
emacs
# in emacs
M-: (require 'use-package) <RET>
```

**Expected behavior**
The `require` expression shouldn't error out

**OS**
`Linux RACEMONSTER 5.10.87 #1-NixOS SMP Fri Dec 17 09:14:42 UTC 2021 x86_64 GNU/Linux`
nix version: `nix (Nix) 2.4`

**Error callstack**
```
(file-missing "Cannot open load file" "No such file or directory" "use-package")
  require(use-package)
  eval-expression((require 'use-package) nil nil 127)
  funcall-interactively(eval-expression (require 'use-package) nil nil 127)
  command-execute(eval-expression)
```

**Comment by GTrunSec** [comment]
> I assume that the submodules didn't get imported in the making of the flake

Yes, you are right.  please try again after #426 is being merged.
