### ISSUE TITLE
Building with Nix Flakes failed

### ISSUE THREAD

**Issue by thiskappaisgrey** [emacs-ng/emacs-ng#454]
**Describe the bug**
Building with nix flakes failed:
![image](https://user-images.githubusercontent.com/16870341/208037482-6ceea814-57bd-4846-a852-6181127ac613.png)

**To Reproduce**
I tried to install EmacsNg using nix flakes, but it failed b/c of sha mismatch.

**Expected behavior**
Installing emacsng with nix flakes should work.

**OS**
Nixos

**Comment by declantsien** [comment]
I've made Nix CI passed on both linux and macOS.
https://github.com/declantsien/emacs-webrender/actions/workflows/nix-flake.yaml
Only with webrender for now.

**Comment by TitouanLeDilavrec** [comment]
i have the same issue when building flakes
