### ISSUE TITLE
`build.rs` not executed unless removed from `Cargo.toml` on recent nightly

### ISSUE THREAD

**Issue by 2e0byo** [emacs-ng/emacs-ng#457]
With recent nightly cargo (`cargo 1.68.0-nightly (1cd6d3803 2023-01-12)` on archlinux) the build script isn't run unless I remove `build = build.rs` from `Cargo.toml`.   This results in build failures from the absence of the generated export files.  Adding `panic!("test")` to `main()` confirms that the script is not being called.

I'm very new to rust but can't find any reference to the `build` key in the cargo book.  Has it been deprecated?

I'm intentionally running against a more recent toolchain, so I've removed `rustup-toolchain`.

**Comment by declantsien** [comment]
build.rs reference is here.
https://doc.rust-lang.org/cargo/reference/build-scripts.html#life-cycle-of-a-build-script

**Comment by declantsien** [comment]
> but can't find any reference to the `build` key in the cargo book. Has it been deprecated?

https://doc.rust-lang.org/cargo/reference/manifest.html#the-build-field

> This results in build failures from the absence of the generated export files.

It has nothing to do with the rust version you are using, just some flaws with previous setup.

**Comment by 2e0byo** [comment]
> > but can't find any reference to the `build` key in the cargo book. Has it been deprecated?
> 
> https://doc.rust-lang.org/cargo/reference/manifest.html#the-build-field

Thanks!  Don't know how I missed that.  I guess I was even newer to rust three weeks ago.

> > This results in build failures from the absence of the generated export files.
> 
> It has nothing to do with the rust version you are using, just some flaws with previous setup.

Ah, right.  What was wrong?  I see you've moved `Cargo.toml` to the top level.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:


>> > This results in build failures from the absence of the generated export files.
>>
>> It has nothing to do with the rust version you are using, just some flaws with previous setup.
>
> Ah, right.  What was wrong?  I see you've moved `Cargo.toml` to the top level.
>

The issue is our crates got build before root crate's build script is finished.

My guess is that Cargo used to run crate's build script before build
it's dependencies. Since our crates output dir is built by the root
crate.

Or maybe it's only not OK when cargo runs with build.jobs>1.

**Comment by 2e0byo** [comment]
On Fri 10 Feb 2023 at 05:59, declantsien ***@***.***> wrote:

> Or maybe it's only not OK when cargo runs with build.jobs>1.

This, I think: I have `make || make` in my build script until
I'd tracked it down.  The failure was always in cargo.
