### ISSUE TITLE
Emacs Crash "Not invalie Emacs_Cursor"

### ISSUE THREAD

**Issue by thiskappaisgrey** [emacs-ng/emacs-ng#478]
**Describe the bug**
Emacs crashes when trying to use the `meow` package (which does something to the cursor):

**To Reproduce**
Use the `flake.nix` with WebRender (which is enabled by default).

This is the minimal config:

```
(setq ng-bootstrap-straight 't)
(unless (fboundp 'ng-bootstrap-straight)
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage)))

(straight-use-package
       '(meow :built-in-version nil :pkg-name nil :type git))
(require 'meow)
(meow-setup)
(meow-global-mode 1)
(message "hello")

```

**Expected behavior**
Emacs to NOT crash.

**OS**
Which os do you use? (`uname -a`) Nixos

**Error callstack**
![image](https://user-images.githubusercontent.com/16870341/220212502-7075c2d8-4617-4aef-982c-f6f74761105c.png)
![image](https://user-images.githubusercontent.com/16870341/220211859-10703063-ab28-4c12-a41d-90465d3a83be.png)

Edit: 
I recompiled  (using `nix build`  to print out the  cursor on error, and I get:
![image](https://user-images.githubusercontent.com/16870341/220215152-48e84db1-da2c-4fd2-8478-4bc6b3143ca4.png)

The cursor is a really big number and I'm not really sure why.. Is there a way for me to edit the rust source without recompiling everything? Thank you.

**Comment by declantsien** [comment]
> The cursor is a really big number and I'm not really sure why..

Have you modified the line with
```_ => panic!("Not invalie Emacs_Cursor {cursor:?}"),``` ? Otherwise I suspect that is the
value of cursor.
Or you can make it recoverable by setting a default value without panic and printing a `log::error!("Not invalie Emacs_Cursor {cursor:?}")`.

>Is there a way for me to edit the rust source without recompiling everything? Thank you.

As far as I know, emacs-ng development workflow should be like
```
- setup local environment. (using nix or other means)
- ./autoconf ./configure from top_srcdir (root of emacs repo)
- cd `src`
- run make
- test emacs by runing `./emacs`
- modify code
- run make again (make/cargo here do increment build)
- test emacs again by runing `./emacs`
...

**Comment by thiskappaisgrey** [comment]
This might be a dumb question but doing:
```
nix develop .#emacsng
[nix-shell] unpackPhase 
[nix-shel] cd ./<unpack-src>
[nix-shell] buildPhase
[nix-shell] ./src/emacs 
```
doesn't reproduce the cursor bug(I didn't change any code). The buildPhase doesn't do any emacs native compilation, and.. I'm guessing it could be related? I might just try a couple of `nix-build`s to see what's going on..

**Comment by thiskappaisgrey** [comment]
Ok, I tried it without `webrender` and it works, and functions in `xfns.c` are defined.. On that note, there doesn't seem to be a configuration option to disable `webrender` (without having to edit `flake.nix` )..

**Comment by declantsien** [comment]
Thanawat Techaumnuaiwit ***@***.***> writes:

> Ok, I tried it without `webrender` and it works, and functions in
> `xfns.c` are defined..

Build without webrender/javascript (comes later I guess) supposed to be as
identical as upstream Emacs. Webrender is not a well tested feature yet.

> On that note, there doesn't seem to be a configuration option to disable `webrender` (without having to edit `flake.nix` )..

There is a configuration option `--with-webrender` from `./configure
--help`. Since you are using nix flake, not sure how that gonna be.
Except define another output?

**Comment by declantsien** [comment]
Thanawat Techaumnuaiwit ***@***.***> writes:


> ```
> nix develop .#emacsng
> [nix-shell] unpackPhase 
> [nix-shel] cd ./<unpack-src>
> [nix-shell] buildPhase
> [nix-shell] ./src/emacs 
> ```

Wow, nix shell can run `unpackPhase/buildPhase`. Didnt know that.

**Comment by 2e0byo** [comment]
btw I love how there are two typos in that error message and everyone (me included) just leaves it alone...

I've had this bug too and didn't look into it (just defaulted it out like that), but as a wild guess we're getting the address of a tagged pointer rather than unpacking it. (That's a 64 bit int with 1 in the MSB, which is a hint, although I can't remember where emacs puts the tag bit.) The chain is unbroken up to `term.rs:winit_define_frame_cursor()` which is called from C land, so I guess the issue must be upstream of the rust code.

**Comment by thiskappaisgrey** [comment]
> There is a configuration option `--with-webrender` from `./configure --help`. Since you are using nix flake, not sure how that gonna be. Except define another output?

I can probably try to write a webrender configuration option for the flake (using emacs-overlay as an example) when I have time.



> btw I love how there are two typos in that error message and everyone (me included) just leaves it alone...
> 
> I've had this bug too and didn't look into it (just defaulted it out like that), but as a wild guess we're getting the address of a tagged pointer rather than unpacking it. (That's a 64 bit int with 1 in the MSB, which is a hint, although I can't remember where emacs puts the tag bit.) The chain is unbroken up to `term.rs:winit_define_frame_cursor()` which is called from C land, so I guess the issue must be upstream of the rust code.

I could try to look into it, but I'm not really sure how to (to reproduce the bug, I have to do a full `nix build` which takes like, 20mins on my machine. Emacs compilation itself doesn't take that long, but native compilation does..   I tried disabling native comp but that doesn't really work well either..).  

If someone who's more knowledgeable on the `nix` workflow sees this, can you let me know what the best workflow is using `nix` thanks!

**Comment by declantsien** [comment]
> If someone who's more knowledgeable on the `nix` workflow sees this, can you let me know what the best workflow is using `nix` thanks!

I found this
`export configureFlags="--prefix=$out --with-readline"`
from https://nixos.wiki/wiki/Nixpkgs/Create_and_debug_packages

**Comment by declantsien** [comment]
I've added  [.#emacsng-noNativeComp](https://github.com/emacs-ng/emacs-ng/pull/480/files)

**Comment by 2e0byo** [comment]
anyway, shouldn't we avoid the panic here?  Much better to log and return the default cursor than panic.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> anyway, shouldn't we avoid the panic here?  Much better to log and return the default cursor than panic.
>

I think that is the idea. Also there is unimplemented
`xw-color-defined-p`. If no one is working on this, I can try to put it
up together sometime later.

**Comment by 2e0byo** [comment]
I deleted my comment on that to have a try but I don't actually know how to call the define macro (or what else to do).  I'll be interested to see how you do it.

**Comment by 2e0byo** [comment]
oh goodness you can just use a fn...

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

>  I don't actually know how to call the define macro (or what else to do).  I'll be interested to see how you do it.
>

Do you mean `lisp_fn` macro? There are plenty examples from `rust_src`
directory. Or you can lookup its definition from
`rust_src/crates/lisp_macros/lib.rs`

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> oh goodness you can just use a fn...
>

Yeah, Emacs NG team has set up some solid ground work.

**Comment by thiskappaisgrey** [comment]
> I think that is the idea. Also there is unimplemented `xw-color-defined-p`. If no one is working on this, I can try to put it up together sometime later.

Oh, with  webrender, it seems that *all functions* from `xfns.c` (in the emacs source) are undefined (I didn't try every function from that file, just a couple) - `xw-color-defined-p` is just one of the functions in that file. A wild guess is that, because you are using webrender, `xfns.c` doesn't get compiled into the emacs source?

**Comment by declantsien** [comment]
Thanawat Techaumnuaiwit ***@***.***> writes:

>> I think that is the idea. Also there is unimplemented `xw-color-defined-p`. If no one is working on this, I can try to put it up together sometime later.
>
> Oh, with  webrender, it seems that *all functions* from `xfns.c` (in the emacs source) are undefined (I didn't try every function from that file, just a couple) - `xw-color-defined-p` is just one of the functions in that file. A wild guess is that, because you are using webrender, `xfns.c` doesn't get compiled into the emacs source?
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/478#issuecomment-1442322956
> You are receiving this because you were assigned.
>
> Message ID: ***@***.***>

`xfns.c` is compiled for x window system, like `pgtkfns.c` is compiled
for PGTK and `nsfns.c` is compiled for `NS`. They are window system
dependent. Implement all lisp function defined in `xfns` for WR(winit)
is a trivial work. But in the end, that should be done if we want WR
(winit) a feature completed Emacs window system.

I doubt that *all functions* from `xfns.c` are undefined. We have
implemented a few in `rust_src/crates/webrender/src/wrterm.rs`.
You should report the missing ones.

There is an alternative way through. Since we want is WR GPU accelerated
rendering, and all the WR needs is an OpenGL context. We can use existing
Emacs window system like X/PGTK/NS, and only replacing the draw part
with WR. Ive been experimenting with PGTK, its doable.

But winit/tao is also attractive thought, by using winit/tao we can
easily reuse some work from Rust Commity like
[wry](https://github.com/tauri-apps/wry) and
[wgpu](https://github.com/gfx-rs/wgpu)
