### ISSUE TITLE
`browse-url winit display` ?

### ISSUE THREAD

**Issue by 2e0byo** [emacs-ng/emacs-ng#482]
I was wondering what the purpose of [this warning](https://github.com/emacs-ng/emacs-ng/blame/master/lisp/net/browse-url.el#L907) is.  Does it just need testing that browse-url works, or are there plans to implement a full browser or something?

FWIW browse-url works fine for me.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> I was wondering what the purpose of [this warning](https://github.com/emacs-ng/emacs-ng/blame/master/lisp/net/browse-url.el#L907) is.  Does it just need testing that browse-url works, or are there plans to implement a full browser or something?
>
> FWIW browse-url works fine for me.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/482
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>

Its a TBD. We probably should disable the warning and keep it as a
comment instead.
