### ISSUE TITLE
Blank window with glutin

### ISSUE THREAD

**Issue by 2e0byo** [emacs-ng/emacs-ng#488]
**Describe the bug**
Current master gives me a blank white window; it's as if it's not actually rendering anything.  I'll dig into why later if nobody else does.

**To Reproduce**

```shell
./configure --with-webrender --enable-wr-glutin --enable-rust-debug
```

**OS**
Which os do you use? (`uname -a`)
6.2.0-arch1-1

**Comment by declantsien** [comment]
Do you mean the second frame or all frames?
Second frame being blank is a known issue, which I fixed in my [branch](https://github.com/declantsien/emacs-ng/commit/af8e8c93af218ca21d257bdc2efdaf6a1f4d8cd9).
![20230224_21h15m29s_grim](https://user-images.githubusercontent.com/51986034/221188372-9256bfe2-be6d-42dc-a9d1-ee1d609f923a.png)

**Comment by 2e0byo** [comment]
all frames.  A breakpoint on `flush` shows it does get there, but stepping through never causes anything to render.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> all frames.  A breakpoint on `flush` shows it does get there, but stepping through never causes anything to render.
>
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/488#issuecomment-1443676720
> You are receiving this because you commented.
>
> Message ID: ***@***.***>

Probably Mutext dead lock from event_loop.rs. I changed some `lock()` to `try_lock()`...
Are there any `Failed to grab a lock` from logs?

`EMACSNG_LOG=wrterm=trace ./emacs`

**Comment by 2e0byo** [comment]
> Probably Mutext dead lock from event_loop.rs. I changed some `lock()` to `try_lock()`... Are there any `Failed to grab a lock` from logs?

No, but hang on, that's a good shout, I'll do some digging on the event loop.

>  `EMACSNG_LOG=wrterm=trace ./emacs`

Call me stupid but I actually couldn't figure out how to filter by crate.  This is enormously useful.  Methinks it should be in the docs (or I just missed it).

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

>> Probably Mutext dead lock from event_loop.rs. I changed some `lock()` to `try_lock()`... Are there any `Failed to grab a lock` from logs?
>
> No, but hang on, that's a good shout, I'll do some digging on the event loop.
>
>>  `EMACSNG_LOG=wrterm=trace ./emacs`
>
> Call me stupid but I actually couldn't figure out how to filter by crate.  This is enormously useful.  Methinks it should be in the docs (or I just missed it).
>
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/488#issuecomment-1443687972
> You are receiving this because you commented.
>
> Message ID: ***@***.***>

It's only added recently 
[here](https://github.com/emacs-ng/emacs-ng/commit/5cb3c2ce5641acef614f6633e7887fc85070abde)
And the usage should be the same as
[env_logger](https://github.com/rust-cli/env_logger/).
Haven't documented anywhere is this repo.

**Comment by 2e0byo** [comment]
I've PRd some docs.  What caught me out was not spotting that `tracing`'s `EnvFilter` works like `env_logging`.  I was just using grep....

**Comment by 2e0byo** [comment]
Nope, not a mutex problem.  None of my quick guesses were right either. I'll dig into this later and figure it out if it's not yet fixed.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> Nope, not a mutex problem.  None of my quick guesses were right either. I'll dig into this later and figure it out if it's not yet fixed.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/488#issuecomment-1443739938
> You are receiving this because you commented.
>
> Message ID: ***@***.***>

You may also want to check `read_input_event` from `crates/webrender/src/term.rs`.
There is another `try_lock` usage there.

```
    let event_buffer = EVENT_BUFFER.try_lock();

if event_buffer.is_err() {
// Try to add some log here...
        return 0;
    }
```

**Comment by 2e0byo** [comment]
I replaced all `try_lock`s with `lock`.  Diffing with the working code should show what it is.

**Comment by declantsien** [comment]
Would you like to give it a try for the code here #490.
I managed to git cherry-picked all the changes from my tao branch in one patch. @2e0byo

**Comment by 2e0byo** [comment]
That now loads.  the scaling code is broken, but it always was with winit.

I'm a bit out of touch atm as I'm madly finishing my thesis :D  But I needed to get Emacs functional first... When the tao/winit split lands upstream I'll try to see what's going on.

I run hyprland mostly and it's definitely more of a problem than e.g. weston.  E.g. it sends *lots* of resize events, so the queue needs to be filtered before processing them, or they take forever to process (and occasionally hang).  But all that is on the list for when the next two chapters are in ;)

**Comment by 2e0byo** [comment]
Bother, actually read the source now.

With `--enable-winit-tao` the WIP branch works for me. (_pace_ some rendering problems which existed before hand).  In any case this issue is definitely closed by it.

**Comment by declantsien** [comment]
> _pace_ some rendering problems which existed before hand

Do you mean the flicking when frame changing focused stated? It can be improved with using tao underline gtk GLContext I think. I may add that later.

For other rendering problems which exist in the issues we can tackle step by step if anyone is interested.

**Comment by declantsien** [comment]
> I'm a bit out of touch atm as I'm madly finishing my thesis :D But I needed to get Emacs functional first... When the tao/winit split lands upstream I'll try to see what's going on.

Good luck with you thesis. I am sticking to PGTK Emacs for now until WR Emacs are ready for daily use.

tao/winit split should happen in the #490. We are waiting for @harryfei 's review. I squashed multi commits into one. There's a lot of changes. Might take some time.
But I am pretty confident about the change though.

**Comment by declantsien** [comment]
> With `--enable-winit-tao` the WIP branch works for me.

Be aware, changed to `--with-winit=tao`.

`--enable-wr-glutin` changed to `--with-wr-gl=glutin`
