### ISSUE TITLE
Use Webrender GPU rendering with PGTK

### ISSUE THREAD

**Issue by declantsien** [emacs-ng/emacs-ng#495]
Ive made it somehow working [here](https://github.com/declantsien/emacs-ng/commits/pgtk_with_webrender), here is a [screencast](https://i.imgur.com/VVzWNLt.mp4)
The child frame/context menu ... just works

`./configure --with-webrender --with-pgtk --with-wr-gl=gtk3`

Some work left:
- [x] what the red color in the screen-cast
- [x] resize alone with the window
- [x] there is white screen flashing after some time

**Comment by 2e0byo** [comment]
This also fixes tooltip windows, which are broken with tao.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> How did you fix the red fill?

I just need to make PGTK using WR render color function[0]. They need to match.

> Separately, this doesn't handle dpi. (And hence mouse.)  Other than
> that I really think this might be the way to go.

If PGTK doesn't work for you. This patch does fix that issue. Not really
sure the dpi issue you are refering[3]. You probably should report
to upstream. Sure they will fix it.

> I dug into tao for some of the broken features and was able to make it
> segfault when it calls out to gtk.  We might be better off with only
> pgtk or winit (IIRC winit has no ffi), i.e. fix things in c-land or in
> rust but not both.

We are building a new winit (tao) window system from stretch, which means there
are a lot of work and boring. If we only want a gpu rendering Emacs.
I've looked at some of the winit/tao source, there are some code looks very
similar to the one in Emacs C code. Which means they are replicating some
code we already have, and winit not even 1.0 yet. Not to mention that
winit has keyboard api 2.0 on the way. I would say winit/tao is a moving target.

> Also our dpi code is entirely backwards anyway, hence having to pass
> the reciprocal of the scale to get the right mouse position.  Brain
> too stupid for thesis today so I'll try to fix it.

You don't have to fix the pgtk issue. Better just send a bug report to
Gnu Emacs[1]. They have more knowledge of what is going on.
Or you should stick to a point where WR Emacs works for you.

[0]:
https://github.com/declantsien/emacs-ng/blob/pgtk_with_webrender/rust_src/crates/webrender/src/color.rs#L97
[1]: https://lists.gnu.org/archive/html/emacs-devel/
[2]: https://lists.gnu.org/archive/cgi-bin/namazu.cgi?query=dpi&submit=Search%21&idxname=emacs-bug-tracker&max=20&result=normal&sort=score

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> This also fixes tooltip windows, which are broken with tao.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/495#issuecomment-1450185048
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

With winit(tao), there are just a lot of unimplemented functionalities.

**Comment by 2e0byo** [comment]
The dpi issue is that we're rendering without scaling, i.e. with a scale factor of 2 only 1/4 of the window is used---the rest is just filled white.  As to dpi being broken I meant where physical/logical dimensions are handled, but that's just in `winit/{frame.rs, output.rs}`.  Told you brain was mush today.

Tooltip windows aren't supported in tao, so a standard window is launched.  But on my hardware it then segfaults somewhere in gtk land.  (It used to panic, but I fixed a trivial issue in tao---you might want to use upstream tao.)  Winit used to load a window fine.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> The dpi issue is that we're rendering without scaling, i.e. with a scale factor of 2 only 1/4 of the window is used---the rest is just filled white.  As to dpi being broken I meant where physical/logical dimensions are handled, but that's just in `winit/{frame.rs, output.rs}`.  Told you brain was mush today.
>
> Tooltip windows aren't supported in tao, so a standard window is launched.  But on my hardware it then segfaults somewhere in gtk land.  (It used to panic, but I fixed a trivial issue in tao---you might want to use upstream tao.)  Winit used to load a window fine.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/495#issuecomment-1450270454
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

Can you try to change this
https://github.com/declantsien/emacs-ng/blob/pgtk_with_webrender/rust_src/crates/webrender/src/display_info.rs#L23 to match your device. Its hard code for pgtk I think.

Needs to make it match PGTK.

**Comment by declantsien** [comment]
Declan Tsien ***@***.***> writes:

>
> Can you try to change this
> https://github.com/declantsien/emacs-ng/blob/pgtk_with_webrender/rust_src/crates/webrender/src/display_info.rs#L23 to match your device. Its hard code for pgtk I think.
>
> Needs to make it match PGTK.

This doesn't help in your case. Its only used when rendering font. Just
understood your dpi issue.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

>>  Winit and tao on Wayland does not support child window last time I checked.
>
> To supports it in theory, as of https://github.com/tauri-apps/tao/commit/f1e8d7556eb9aea89769a9b38407e8fcd12675af.  In practice `examples/parentwindow.rs` just launches two standard windows under hyprland, but that might be the compositor being funny.  PGTK child windows are handled correctly, however.
>
> Regardless PGTK is a much better way to get a gpu-accelerated emacs with minimal fuss.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/495#issuecomment-1450634851
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

I am aware of that. gtk's `with_transient_for` does not qualify as the child frame concept
from Emacs. PGTK has a hacky implementation for child frame.

> The dpi issue is that we're rendering without scaling, i.e. with a scale factor of 2 only 1/4 of
> the window is used---the rest is just filled white.  As to dpi being broken I meant where
> physical/logical dimensions are handled, but that's just in `winit/{frame.rs, output.rs}`.  

Hey, can you share some screenshots regarding this scaling issue when
using the WR/PGTK build.

**Comment by declantsien** [comment]
> * there is white screen flashing after some time

After playing around with `MESA_LOADER_DRIVER_OVERRIDE`, I don't have this issue anymore.
Finally, I am having a ready-to-use Webrender rendered Emacs.
