### ISSUE TITLE
Pure Rust font stack for wr_glyph_rasterizer

### ISSUE THREAD

**Issue by declantsien** [emacs-ng/emacs-ng#498]
https://github.com/emacs-ng/emacs-ng/issues/498#issuecomment-1490348713

**Comment by 2e0byo** [comment]
Isn't this down to automatic composition [not being implemented](https://github.com/emacs-ng/emacs-ng/blob/master/rust_src/crates/webrender/src/draw_canvas.rs#L434) ?

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> Isn't this down to automatic composition [not being implemented](https://github.com/emacs-ng/emacs-ng/blob/master/rust_src/crates/webrender/src/draw_canvas.rs#L434) ?
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/498#issuecomment-1450601771
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

Seems like that is the case.

**Comment by declantsien** [comment]
Hit this WR [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1565588). WebRender currently does not work with `Noto Color Emoji`.
```
2023-03-15T02:04:03.872358Z ERROR wr_glyph_rasterizer::platform::unix::font: Unable to set glyph size and transform: 23
2023-03-15T02:04:03.872373Z DEBUG wr_glyph_rasterizer::platform::unix::font:    [662] for size 16.0 and scale (1.0, 1.0) from font FontKey(IdNamespace(1), 5)
2023-03-15T02:04:03.872393Z ERROR wr_glyph_rasterizer::platform::unix::font: Unable to set glyph size and transform: 23
2023-03-15T02:04:03.872404Z DEBUG wr_glyph_rasterizer::platform::unix::font:    [260158] for size 16.0 and scale (1.0, 1.0) from font FontKey(IdNamespace(1), 5)```

**Comment by declantsien** [comment]
Code path for color font is not limited to glyph automatic composite.
It used for glyph_type::CHAR_GLYPH too.

Better if WebRender [GlyphInstance](https://doc.servo.org/webrender_api/struct.GlyphInstance.html) adds supports for this, otherwise we have to manually draw font png/svg images.

While waiting for WebRender [adding support for Color Font](https://bugzilla.mozilla.org/show_bug.cgi?id=1565588). I am happy with just disable Noto Color Emoji for now.

**Comment by declantsien** [comment]
I recently realized that WebRender has a hard C dependencies (freetype2/harfbuzz), while we'd prefer font stack using Rust(fontdb/ttf_parser/rustybuzz/fontdue/swash etc).

I've experimenting with replacing WebRender wr_glyph_rasterizer with [fontdue](https://github.com/mooman219/fontdue). It turns out doable. My WebRender branch using fontdue is [here](https://github.com/declantsien/webrender/tree/fontdue) and ng branch [here](https://github.com/declantsien/emacs-ng/tree/fontdue).

Tasks:

- [ ] Make sure wr_glyph_rasterizer fontdue backend works well with WebRender's [distribute_across_threads](https://github.com/declantsien/webrender/blob/fontdue/wr_glyph_rasterizer/src/font.rs#L127)

- [ ] Patch fontdue to work with ttf_parser's [glyph_raster_image](https://docs.rs/ttf-parser/latest/ttf_parser/struct.Face.html#method.glyph_raster_image) and [glyph_svg_image](https://docs.rs/ttf-parser/latest/ttf_parser/struct.Face.html#method.glyph_svg_image). This is for color emojis.
https://github.com/mooman219/fontdue/issues/133

- [ ] Patch fontdue for font shaping(ligatures etc) support
https://github.com/mooman219/fontdue/issues/127

- [ ] What about WebRender Mono [FontRenderMode](https://doc.servo.org/webrender_api/font/enum.FontRenderMode.html)

- [ ] Some [WR FontInstanceFlags](https://doc.servo.org/webrender_api/font/struct.FontInstanceFlags.html) is not implemented, also we haven't use them in Emacs

There are some font concepts I am not sure whether there are involved here.
- [ ] Font kerning ? https://github.com/keiya01/font-kerning.git
- [ ] Glyph cache using GPU(atlas?) https://github.com/ryanisaacg/elefont.git
- [ ] Text layout is not necessary since Emacs redisplay is doing all the calculation?
...

**Comment by declantsien** [comment]
png/svg fonts is working using patched [`wr_glyph_rasterizer`](https://github.com/declantsien/webrender/tree/fontdue).
![swappy-20230402_212837](https://user-images.githubusercontent.com/51986034/229356310-84b08093-f839-4842-b2d2-5c4b2e1ee984.png)
![swappy-20230402_212305](https://user-images.githubusercontent.com/51986034/229356322-d2b27064-714e-48cb-ac00-c933b04a566b.png)

**Comment by rice7th** [comment]
perhaps Cosmic text?

**Comment by declantsien** [comment]
> perhaps Cosmic text?

Cosmic text doesn't really fit into Emacs IMO. Emacs layout text itself.
However the glyph rendering library [`swash`](https://docs.rs/swash/latest/swash/index.html) they use is what we need which also support complex text shaping.
I manage to make the emoji and shaping working here #564.

Choosing swash over [fontdue](https://github.com/mooman219/fontdue) which I mentioned in other comments, is that fontdue doesn't support emoji rendering, also we have to find another rust shaping library.

Interestingly, we have this [elisp OTF/TTF font loader and renderer ](https://github.com/jollm/fontsloth) which is inspired by fontdue.

**Comment by declantsien** [comment]
![swappy-20240305_104850](https://github.com/emacs-ng/emacs-ng/assets/51986034/1c75b0bf-94eb-48ba-bc26-f66437d9734f)

**Comment by rice7th** [comment]
Allsortrs by yeslogic seems to be a powerful shaping library

**Comment by declantsien** [comment]
> Allsortrs by yeslogic seems to be a powerful shaping library

I think we wouldn't mind having a new Emacs font driver implemented in Allsort!
If someone is willing to write the code for it 🙂

**Comment by rice7th** [comment]
Oh well I don't have that much experience with font shaping libraries 😅 but if I find enough time maybe this summer I can give it a look
