### ISSUE TITLE
Broken nix build

### ISSUE THREAD

**Issue by guskovd** [emacs-ng/emacs-ng#523]
**To Reproduce**
```shell
nix build github:emacs-ng/emacs-ng --option substituters "https://emacsng.cachix.org" --option trusted-public-keys "emacsng.cachix.org-1:i7wOr4YpdRpWWtShI8bT6V7lOTnPeI7Ho6HaZegFWMI=" -o emacsNg
```
output:
```shell
error: builder for '/nix/store/9ik0f6jnz1gfx66yglprrh3dga7r5h7j-emacs-ng-30.0.50.drv' failed with exit code 2;
       last 10 log lines:
       > *** "make all" failed with exit status 2.
       > ***
       > *** You could try to:
       > *** - run "make bootstrap", which might fix the problem
       > *** - run "make V=1", which displays the full commands invoked by make,
       > ***   to further investigate the problem
       > ***
       > make[1]: *** [Makefile:428: advice-on-failure] Error 2
       > make[1]: Leaving directory '/tmp/nix-build-emacs-ng-30.0.50.drv-0/hwr6w3a323wlp559k3a31si5a102nsqx-source'
       > make: *** [Makefile:384: all] Error 2
       For full logs, run 'nix log /nix/store/9ik0f6jnz1gfx66yglprrh3dga7r5h7j-emacs-ng-30.0.50.drv'.
```

**Comment by declantsien** [comment]
Can you attach output from cmd
```
nix log /nix/store/9ik0f6jnz1gfx66yglprrh3dga7r5h7j-emacs-ng-30.0.50.drv
```

Are you building on apple silicon (M1/aarch64-darwin) by any chance? If so, see #336

**Comment by guskovd** [comment]
> Can you attach output from cmd
> 
> ```
> nix log /nix/store/9ik0f6jnz1gfx66yglprrh3dga7r5h7j-emacs-ng-30.0.50.drv
> ```
> 
> Are you building on apple silicon (M1/aarch64-darwin) by any chance? If so, see #336

I build on Linux Laptop (Lenovo) x64
[log.txt](https://github.com/emacs-ng/emacs-ng/files/11010732/log.txt)

**Comment by declantsien** [comment]
Will you try to build with

```nix build github:emacs-ng/emacs-ng#emacsng --option substituters "https://emacsng.cachix.org" --option trusted-public-keys "emacsng.cachix.org-1:i7wOr4YpdRpWWtShI8bT6V7lOTnPeI7Ho6HaZegFWMI="```

devShell from `flake.nix` needs updates. see https://github.com/emilk/egui/discussions/1587

**Comment by guskovd** [comment]
> 

```shell
nix build github:emacs-ng/emacs-ng#emacsng --option substituters "https://emacsng.cachix.org" --option trusted-public-keys "emacsng.cachix.org-1:i7wOr4YpdRpWWtShI8bT6V7lOTnPeI7Ho6HaZegFWMI="
error: builder for '/nix/store/9ik0f6jnz1gfx66yglprrh3dga7r5h7j-emacs-ng-30.0.50.drv' failed with exit code 2;
       last 10 log lines:
       > *** "make all" failed with exit status 2.
       > ***
       > *** You could try to:
       > *** - run "make bootstrap", which might fix the problem
       > *** - run "make V=1", which displays the full commands invoked by make,
       > ***   to further investigate the problem
       > ***
       > make[1]: *** [Makefile:428: advice-on-failure] Error 2
       > make[1]: Leaving directory '/tmp/nix-build-emacs-ng-30.0.50.drv-0/hwr6w3a323wlp559k3a31si5a102nsqx-source'
       > make: *** [Makefile:384: all] Error 2
       For full logs, run 'nix log /nix/store/9ik0f6jnz1gfx66yglprrh3dga7r5h7j-emacs-ng-30.0.50.drv'.
```

**Comment by declantsien** [comment]
Danil Guskov ***@***.***> writes:

I have no idea then. The build from CI[0] works just fine. Maybe try to
remove `--option substituters "https://emacsng.cachix.org"`?

[0]:
https://github.com/emacs-ng/emacs-ng/actions/runs/4454166198/workflow#L36

**Comment by guskovd** [comment]
> Danil Guskov ***@***.***> writes: I have no idea then. The build from CI[0] works just fine. Maybe try to remove `--option substituters "[https://emacsng.cachix.org"`](https://emacsng.cachix.org%22%60)? [0]: https://github.com/emacs-ng/emacs-ng/actions/runs/4454166198/workflow#L36

Same result :(

**Comment by GTrunSec** [comment]
please try the command with `--refresh` flag.
nix build github:emacs-ng/emacs-ng --refresh --option substituters "https://emacsng.cachix.org" --option trusted-public-keys "emacsng.cachix.org-1:i7wOr4YpdRpWWtShI8bT6V7lOTnPeI7Ho6HaZegFWMI=" -o emacsNg

**Comment by guskovd** [comment]
> please try the command with `--refresh` flag. nix build github:emacs-ng/emacs-ng --refresh --option substituters "https://emacsng.cachix.org" --option trusted-public-keys "emacsng.cachix.org-1:i7wOr4YpdRpWWtShI8bT6V7lOTnPeI7Ho6HaZegFWMI=" -o emacsNg

same result

**Comment by guskovd** [comment]
> > Can you attach output from cmd
> > ```
> > nix log /nix/store/9ik0f6jnz1gfx66yglprrh3dga7r5h7j-emacs-ng-30.0.50.drv
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Are you building on apple silicon (M1/aarch64-darwin) by any chance? If so, see #336
> 
> I build on Linux Laptop (Lenovo) x64 [log.txt](https://github.com/emacs-ng/emacs-ng/files/11010732/log.txt)

Problem 1: I think it's pretty obvious from the log that libXcursor is missing in flake.nix

**Comment by guskovd** [comment]
... ... However, just adding libXcursor to flake.nix introduces a new problem
[log2.txt](https://github.com/emacs-ng/emacs-ng/files/11038312/log2.txt)

**Comment by guskovd** [comment]
I found workaround:

```diff
diff --git a/flake.nix b/flake.nix
index 222f4e4d3b..1e58da71e0 100644
--- a/flake.nix
+++ b/flake.nix
@@ -134,6 +134,7 @@
             #withGLX
             rpathLibs = with xorg;
               lib.optionals (stdenv.isLinux && withWebrender) [
+                libXcursor
                 libX11
                 libXrandr
                 libXi
@@ -208,8 +209,8 @@
                 "--with-dumping=pdumper"
               ]
               ++ lib.optionals withWebrender [
-                "--with-winit"
-                "--with-webrender"
+                # "--with-winit"
+                # "--with-webrender"
               ]
               ++ lib.optionals (stdenv.isDarwin && withWebrender) [
                 "--disable-ns-self-contained"
@@ -313,9 +314,9 @@
               name = "${oa.name}-wr-pgtk";
               configureFlags =
               (
-                  prev.lib.subtractLists [
-                    "--with-winit"
-                  ]
+                  # prev.lib.subtractLists [
+                  #   "--with-winit"
+                  # ]
                   oa.configureFlags
               );
             }
```

**Comment by 2e0byo** [comment]
The workaround is just not to build with webrender/winit at all.  That might be acceptable to you, but you're basically getting stock emacs with that atm.  Still, if you want to work on JS or just play it might be fine.

**Comment by stefanhusmann** [comment]
Btw, it is not a nix issue. The same applies for Arch Linux - als the same "workaround".

**Comment by 2e0byo** [comment]
@stefanhusmann how are you building on arch?  It's def. possible to build on arch fine---that's my dev env..

**Comment by 2e0byo** [comment]
Ah no hang on, something has broken our configure.ac. @declantsien did the merge-upstream script overwrite it?

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> Ah no hang on, something has broken our configure.ac. @declantsien did the merge-upstream script overwrite it? 
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/issues/523#issuecomment-1484328259
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>

Hmm, CI tests/checks seems Ok...

I think there are two issues regarding this:

- Winit frame related code should not be invoked when compiling
  elisp/info files
- What to do when Winit failed to initialize Wayland/X11 backends

Since I am running WR/PGTK these days, I have no plan to fix these as yet.

**Comment by 2e0byo** [comment]
> Hmm, CI tests/checks seems Ok...

Sorry this was noise, I was being stupid late at night.  I forgot you do issues by email so I edited that comment rather than add another.

**Comment by declantsien** [comment]
Kindly refer to this comment:  
https://github.com/emacs-ng/emacs-ng/issues/530#issuecomment-1524625177
Please reopen the issue if the issue continues. 
@guskovd
