### ISSUE TITLE
Build error Arch Linux - also the same "workaround".

### ISSUE THREAD

**Issue by stefanhusmann** [emacs-ng/emacs-ng#530]
Btw, it is not a nix issue. The same applies for Arch Linux - als the same "workaround".

_Originally posted by @stefanhusmann in https://github.com/emacs-ng/emacs-ng/issues/523#issuecomment-1484121790_

**Comment by stefanhusmann** [comment]
As #523 should be kept clean I answer here. I use this build function: 
``` bash
build() {
  cd ${pkgname}-0.0.${_fix_commit}
  RUSTUP_TOOLCHAIN=$(cat rust-toolchain)
  ./autogen.sh
  ./configure CFLAGS="-Wl,-rpath,shared -Wl,--disable-new-dtags" \
              --prefix=/usr \
	       --sysconfdir=/etc \
	       --libexecdir=/usr/lib \
	       --localstatedir=/var \
              --with-json \
	       --with-modules \
	       --with-compress-install \
	       --with-threads \
	       --with-included-regex \
	       --with-zlib \
	       --with-libsystemd \
	       --with-rsvg \
	       --without-imagemagick \
	       --with-gpm \
	       --without-xaw3d \
	       --with-dbus \
	       --without-pop \
	       --with-mailutils \
	       --with-gsettings \
	       --with-webrender \
	       --with-winit \
	       --disable-build-details 
  
  make V=1 PATH="$HOME/.rustup/toolchains/${RUSTUP_TOOLCHAIN}-$(uname -m)-unknown-linux-gnu/bin:$PATH" bootstrap
  make pdf
}
```

**Comment by stefanhusmann** [comment]
Thanks for your efforts, but I see no difference.

**Comment by declantsien** [comment]
Hey, thanks for testing. Would you like to try again?
I figured out the error arises when compiling `elc` files using `../src/emacs --batch` during the build.
I think, the build process should be fine without this issue now.

However, I am not sure whether the issue will show up when you try manually running Emacs.
But that relates to the local environment configuration.

**Comment by stefanhusmann** [comment]
I gave it a try using https://github.com/declantsien/emacs-ng.git 's most recent commit, but it is still not working with a segfault at the compilation step. Btw, most of the time org-modes elisp files are involved, but this is not always the case. In another attempt I also saw gnus files being in process.

**Comment by declantsien** [comment]
My apologies, I forgot to merge the changes into master. Care to attempt that again?
