### ISSUE TITLE
Remove uses of `static mut`

### ISSUE THREAD

**Issue by ubolonton** [emacs-ng/emacs-ng#63]
`static mut` is extremely hard to use correctly: https://github.com/rust-lang/rust/issues/53639.

We should use [once_cell](https://github.com/matklad/once_cell) instead. (It can also replace our uses of `lazy_static!`.)

**Comment by DavidDeSimone** [comment]
https://github.com/emacs-ng/emacs-ng/pull/64 addressed our JavaScript layer's usage of static mut, however there are still a number of uses in the codebase, including the code generated from `#[lisp_fn]`, the `Lisp_Fwd` struct, and almost all of bindgen. bindgen will be harder to tackle, but we can still work the other cases.
