### ISSUE TITLE
allow using lisp_fn macro in other crates than the main crate

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#65]
Currently the generation of lisp functions is only possible in the path rust_src/src. Since we also want to be able to define lisp functions in different crates we have to adjust the code that's used to create them.

**Comment by DavidDeSimone** [comment]
It seems like we want a build step between building the products of lib-src, but prior to building temacs, that parsing all of our rust, looks for `#[lisp_fn]`, and generates a per crate export function, i.e. `init_lisp_util_syms`, `init_lisp_syms`, etc. 

rust_src/src/lib.rs then has the master export function `init_rust_syms` that calls each crate's individual function.
