### ISSUE TITLE
Generate docs

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#71]
I think we should consider using something like lsp-mode to generate our docs(https://emacs-lsp.github.io/lsp-mode/) once we have too much documentation in our readme.

**Comment by ericdallo** [comment]
LMK if need any help with that :)

**Comment by ericdallo** [comment]
https://emacs-ng.github.io/emacs-ng/
@brotzeit should we close this?

**Comment by brotzeit** [comment]
@ericdallo yeah that's exactly what I had in mind.
