### ISSUE TITLE
Add support for Nix/NixOS

### ISSUE THREAD

**Issue by ericdallo** [emacs-ng/emacs-ng#73]
I'm a NixOS user and I'm creating this just to track adding support to install `emacs-ng` using nix since NixOS users can only install it that way. 

This is how emacs is built on nix ATM: https://github.com/nix-community/emacs-overlay

I think if we have emacs-ng shipped, it could be really useful for an easy install for final users where it'd be just:
```
nix-env -iA emacs-ng
```

note: `nix` is a package manager that can be installed in any unix based OS.

**Comment by brotzeit** [comment]
@kidd started working on it https://github.com/nix-community/emacs-overlay/issues/114

**Comment by brotzeit** [comment]
Thanks everybody who helped adding nix support! Documentation can be found here https://emacs-ng.github.io/emacs-ng/nix-develop/
