### ISSUE TITLE
Make a JS/TS "Getting Started" Guide 

### ISSUE THREAD

**Issue by DavidDeSimone** [emacs-ng/emacs-ng#94]
This would be different from https://github.com/emacs-ng/emacs-ng/issues/71 in that it would be more of a new user tutorial "step-by-step" series the user could follow to make emacs-ng do things, vs. a description of function behavior.

**Comment by petr-tik** [comment]
I would say there are several different tutorials:
1. Running tests/benchmarks (people who will build this from source are likely to be interested in that I think) 
the readme mentions that JS outperforms lisp, but doesn't give instructions how to reproduce the benchmark
2. Writing javascript to execute in emacs-ng/porting existing npm package to be emacs-ng runnable
3. JS package management and integrating JS functions to be called by existing elisp

I ran fuzzy-search from [here](https://github.com/DavidDeSimone/ng-fuzzy-search) and then I ran fuzzy-search and it was async! 

It would be amazing if we can integrate an async backend to a framework like ivy/selectrum or even write a new async backend. I work in a large codebase on a remote machine with slow storage that I have to tramp into and the usually interactive commands are dog slow and block the rest of my emacs to execute. I don't know how applicable it is, but I would be happy to contribute something to solve that (my rust is better than my C or JS though)

**Comment by DavidDeSimone** [comment]
I don't know where the best place to document on how to reproduce the benchmark it, though it's pretty simple:

benchmark.el
```lisp
(defun fibonacci(n)
  (if (<= n 1)
      n
    (+ (fibonacci (- n 1)) (fibonacci (- n 2)))))

(let ((time (current-time)))
  (fibonacci 40)
  (message "%.06f" (float-time (time-since time))))

(let ((time (current-time)))
  (eval-js-file "./fib.js")
  (message "%.06f" (float-time (time-since time))))
```
fib.js

```js
const fib = (n) => {
    if (n <= 1) {
	return n;
    }

    return fib(n - 1) + fib(n - 2);
};

fib(40);
```
The latest head of master without nativecomp clocks in with this on my machine:

lisp: 58.584704
JS:  1.203173

time in seconds.

**Comment by DavidDeSimone** [comment]
I'm going to mark this complete, and will track additional guides under a new issue.
